In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

###Tarif Dataset
def load_house_attributes (inputPath):
  cols= ["bedroom", "bathroom", "area", "ZipCode", "Price"]
  df=pd.read_csv(inputPath, sep= " ", header=None, names=cols)
  zipcodes=df["ZipCode"].value_counts()
  zipcodes=df["ZipCode"].value_counts().keys().to_list()
  counts=df["ZipCode"].value_counts().to_list()
  print(zipcodes)
  print(counts)
  ###Hazf Zipcode haye ba tedad <25
  for (zipcode, count) in zip (zipcodes, counts):
    if count<25:
      indx=df[df["ZipCode"]==zipcode].index
      df.drop(indx, inplace=True)
  return df
###Normal Kardan Vizhegi haye Continuouse:
def preprocessing_house_attribute (train, test):
  continuous= ["bedroom", "bathroom", "area"]
  sc=StandardScaler()
  trainContinuous=sc.fit_transform(train[continuous])
  testContinuous=sc.transform(test[continuous])
  print(trainContinuous.shape)
  print(testContinuous.shape)
  ###OneHotEncoder dar ZipCode(Categorial):
  encoder=OneHotEncoder(sparse=False)
  trainCategorial=encoder.fit_transform(np.array(train["ZipCode"]).reshape(-1,1))
  testCategorial=encoder.transform(np.array(test["ZipCode"]).reshape(-1,1))
  print(trainCategorial)
  print(trainCategorial.shape)
  trainX=np.hstack([trainCategorial, trainContinuous])
  testX=np.hstack([testCategorial, testContinuous])
  print(trainX.shape)
  print(testX.shape)
  print(trainCategorial)
  return trainX, testX

###Farakhani File
df=load_house_attributes ("/content/drive/MyDrive/HousesInfo.txt")
###Normal Kardan Label
train, test=train_test_split(df,test_size=0.2, random_state=42)
maxPrice=train["Price"].max()
trainX, testX= preprocessing_house_attribute(train, test)
trainY=train["Price"]/maxPrice
testY=test["Price"]/maxPrice

###Model Karan dataset
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(trainX, trainY)
print(model.coef_)

###Peyda kardan Deghat 
from sklearn.metrics import mean_absolute_percentage_error
preds= model.predict(testX)
mape= mean_absolute_percentage_error (testY, preds)
print("mape: {:.2f}".format(mape))


[92276, 93510, 93446, 92880, 94501, 91901, 92677, 94531, 96019, 85255, 92021, 85266, 93111, 81524, 95220, 92802, 85262, 62234, 62214, 98021, 85377, 91752, 60002, 81418, 62025, 92253, 60016, 92692, 90265, 62034, 62088, 91915, 94565, 95008, 90803, 90038, 93314, 93720, 93924, 92040, 90211, 94568, 92543, 62249, 85331, 93105, 60046, 36372, 81521]
[100, 60, 54, 49, 41, 32, 26, 22, 12, 12, 11, 11, 11, 11, 10, 9, 9, 7, 4, 4, 3, 3, 3, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
(289, 3)
(73, 3)
[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
(289, 7)
(289, 10)
(73, 10)
[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
[-0.00216541 -0.04708977  0.0634664  -0.06610923 -0.0002863  -0.00295073
  0.05513504 -0.00325816  0.0138258   0.03955316]
mape: 0.32
